### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by talgalili** [yonicd/Elections#2]
Code run and error:

``` r
> shiny::runGitHub("Elections","yonicd")
Downloading https://github.com/yonicd/Elections/archive/master.tar.gz
Error in eval(expr, envir, enclos) : 
  cannot join on columns 'Publisher' x 'Publisher' : found multiple encodings in character string
```

**Comment by yonicd** [comment]
The error is because of the locale, are you using windows or unix?

the unix seems to run ok since the app is running on the shiny servers. the problem is the local windows charset of users. right now the least costly thing is have them write

``` r
Sys.setlocale("LC_ALL", "Hebrew_Israel.1255")
shiny::runGitHub("Elections","yonicd")
```

when i put that locale change in the header of the global it doesnt help, it always sees the global.r as not saved in utf-8, but i have tried resaving it with encoding a few times without success.
